import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Layout/Navbar"; // Navbar কম্পোনেন্ট ইমপোর্ট করুন
import Footer from "./Components/Layout/Footer"; // Footer কম্পোনেন্ট ইমপোর্ট করুন
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar /> {/* Navbar এখানে যোগ করুন */}
        {children}
        <Footer /> {/* Footer এখানে যোগ করুন */}
      </body>
    </html>
  );
}
